<div id="tree_help_common">
  <table id="help_mouse">
    <tr>
      <th colspan="2">Mouse</th>
    </tr>
    <tr>
      <td>click<br> folder marker &nbsp;&nbsp; ► &nbsp;,&nbsp; ▼</td>
      <td>open/close folder</td>
    </tr>
    <tr>
      <td>click<br> item</td>
      <td>select/unselect</td>
    </tr>
    <tr>
      <td>double-click<br> lambda/macro/list symbol item</td>
      <td>create folder<br> with referenced symbols at top</td>
    </tr>
  </table>

  <table id="help_keyboard">
    <tr>
      <th colspan="2">Keyboard navigation at selected item</th>
    </tr>
    <tr>
      <td>&#8594;</td><td>open folder</td>
    </tr>
    <tr>
      <td>&#8592;</td><td>close folder</td>
    </tr>
    <tr>
      <td>&#8593; &#8595;</td><td>navigate up/down to next item</td>
    </tr>
    <tr>
      <td>&lt;Return&gt;<br>at selected lambda/macro/list symbol item</td>
      <td>create folder<br> with referenced symbols at top</td>
    </tr>
  </table>
</div>
